spring:
  application:
    name: BlogAPI

  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: Hesoyam21@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Pode ser: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect